{{- if and .Values.webhook.certManager.enabled (or .Values.controllers.pipeline.enabled .Values.controllers.collector.enabled .Values.controllers.collectorDiscovery.enabled .Values.controllers.externalAttributeSync.enabled .Values.controllers.remoteAttributePolicy.enabled .Values.controllers.tenantPolicy.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "fleet-management-operator.fullname" . }}-webhook
  labels:
    {{- include "fleet-management-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "fleet-management-operator.fullname" . }}-webhook
  - {{ include "fleet-management-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  - {{ include "fleet-management-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.webhook.certManager.issuerRef.name }}
    kind: {{ .Values.webhook.certManager.issuerRef.kind }}
  secretName: {{ include "fleet-management-operator.fullname" . }}-webhook-certs
{{- end }}
