{{- if include "fleet-management-operator.webhooksEnabled" . }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "fleet-management-operator.fullname" . }}-validating-webhook
  labels:
    {{- include "fleet-management-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "fleet-management-operator.fullname" . }}-webhook"
  {{- end }}
webhooks:
{{- if .Values.controllers.collector.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-collector
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vcollector.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectors
  sideEffects: None
{{- end }}
{{- if .Values.controllers.collectorDiscovery.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-collectordiscovery
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vcollectordiscovery.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectordiscoveries
  sideEffects: None
{{- end }}
{{- if .Values.controllers.externalAttributeSync.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-externalattributesync
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vexternalattributesync.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - externalattributesyncs
  sideEffects: None
{{- end }}
{{- if .Values.controllers.pipeline.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-pipeline
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vpipeline.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
{{- end }}
{{- if .Values.controllers.pipelineDiscovery.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-pipelinediscovery
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vpipelinediscovery.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelinediscoveries
  sideEffects: None
{{- end }}
{{- if .Values.controllers.remoteAttributePolicy.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-remoteattributepolicy
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vremoteattributepolicy.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteattributepolicies
  sideEffects: None
{{- end }}
{{- if .Values.controllers.tenantPolicy.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "fleet-management-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-fleetmanagement-grafana-com-v1alpha1-tenantpolicy
    {{- if .Values.webhook.caBundle }}
    caBundle: {{ .Values.webhook.caBundle | quote }}
    {{- end }}
  failurePolicy: Fail
  name: vtenantpolicy.kb.io
  timeoutSeconds: 5
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenantpolicies
  sideEffects: None
{{- end }}
{{- end }}
