package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// eventDecl is one (controller, reason, eventtype) triple. Multiple call sites
// for the same reason are collapsed; the first message format encountered wins
// for the Trigger column.
type eventDecl struct {
	Reason    string
	EventType string // Normal | Warning
	Trigger   string // first non-empty messageFmt encountered
	Source    string // file:line of the first call site
}

type eventGroup struct {
	Controller string
	File       string
	Events     []eventDecl
}

// generateEvents is the entrypoint for the `events` subcommand. It walks
// every controller source file under internal/controller/ for emitEvent /
// emitEventf / Recorder.Event* call sites, resolves reason constants from the
// per-controller `*EventReason*` const blocks, and renders one table per
// controller.
func generateEvents(root string) ([]byte, error) {
	dir := filepath.Join(root, "internal", "controller")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	groups := make([]eventGroup, 0, len(entries))
	for _, ent := range entries {
		name := ent.Name()
		if ent.IsDir() || !strings.HasSuffix(name, "_controller.go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		full := filepath.Join(dir, name)
		evs, err := extractEvents(root, full)
		if err != nil {
			return nil, fmt.Errorf("extract %s: %w", name, err)
		}
		if len(evs) == 0 {
			continue
		}
		controller := controllerName(name)
		groups = append(groups, eventGroup{
			Controller: controller,
			File:       filepath.Join("internal", "controller", name),
			Events:     evs,
		})
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].Controller < groups[j].Controller })

	tmpl, err := template.New("events").Parse(eventsTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, groups); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const eventsTemplate = `<!--
Auto-generated by hack/docgen. Do not edit by hand.
Run ` + "`make docs`" + ` after touching emitEvent / Recorder.Event* call sites in
internal/controller/*.go.
-->

# Event Reference

Each controller emits Kubernetes events on significant reconcile outcomes.
Events are user-facing log text — surface them via:

` + "```" + `
kubectl describe <kind> <name>
kubectl get events --field-selector involvedObject.kind=<Kind>
` + "```" + `

Reasons are stable PascalCase identifiers and may be matched on directly. Event
type ` + "`Warning`" + ` indicates the controller could not complete its work; ` + "`Normal`" + `
indicates a routine state transition.

For status-condition reasons (a separate, also-stable surface), see
[conditions.md](conditions.md).
{{ range . }}
## {{ .Controller }}

Source: [{{ .File }}](../{{ .File }})

| Reason | Type | Trigger |
| --- | --- | --- |
{{- range .Events }}
| ` + "`{{ .Reason }}`" + ` | {{ .EventType }} | {{ .Trigger }} |
{{- end }}
{{ end }}
`

// extractEvents walks a single controller file. Two passes:
//
//  1. collect const-block string mappings for every `*EventReason*` identifier.
//  2. walk CallExpr nodes looking for emitEvent / emitEventf / Recorder.Event /
//     Recorder.Eventf and capture (eventtype, reason, message) tuples.
//
// Reason resolution prefers the const map; a string-literal reason is taken
// verbatim. EventType resolves the corev1.EventType{Normal,Warning} selector
// to "Normal" / "Warning".
func extractEvents(root, path string) ([]eventDecl, error) {
	fset := token.NewFileSet()
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	relPath, err := filepath.Rel(root, path)
	if err != nil {
		relPath = path
	}

	consts := collectEventReasonConsts(file)

	type key struct {
		Reason, EventType string
	}
	seen := map[key]eventDecl{}
	order := []key{} // preserve first-seen order for stable output

	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		// Match either `r.emitEvent(...)`, `r.emitEventf(...)`,
		// `r.Recorder.Event(...)`, `r.Recorder.Eventf(...)`.
		if !isEventCall(call) {
			return true
		}
		if len(call.Args) < 3 {
			return true
		}
		etype := resolveEventType(call.Args[1])
		if etype == "" {
			return true
		}
		reason := resolveReason(call.Args[2], consts)
		if reason == "" {
			return true
		}
		var trigger string
		if len(call.Args) >= 4 {
			trigger = strings.TrimSpace(concatStringExpr(call.Args[3]))
			trigger = strings.ReplaceAll(trigger, "|", "\\|")
			trigger = strings.ReplaceAll(trigger, "\n", " ")
		}
		k := key{Reason: reason, EventType: etype}
		if _, ok := seen[k]; ok {
			return true
		}
		pos := fset.Position(call.Pos())
		seen[k] = eventDecl{
			Reason:    reason,
			EventType: etype,
			Trigger:   trigger,
			Source:    fmt.Sprintf("%s:%d", relPath, pos.Line),
		}
		order = append(order, k)
		return true
	})

	out := make([]eventDecl, 0, len(order))
	for _, k := range order {
		out = append(out, seen[k])
	}
	// Sort by EventType (Warning first as more diagnostically interesting), then Reason.
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].EventType != out[j].EventType {
			return out[i].EventType > out[j].EventType // "Warning" > "Normal" alphabetically
		}
		return out[i].Reason < out[j].Reason
	})
	return out, nil
}

// collectEventReasonConsts walks top-level GenDecl const blocks for any
// identifier whose name contains "EventReason" and whose RHS is a string
// literal. The codebase uses both `eventReasonSynced` (pipeline) and
// `collectorEventReasonSynced` (collector) — the substring match catches both.
func collectEventReasonConsts(file *ast.File) map[string]string {
	out := map[string]string{}
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, n := range vs.Names {
				// Case-insensitive: pipeline_controller.go uses
				// `eventReasonSynced`, collector_controller.go uses
				// `collectorEventReasonSynced`. Both should match.
				if !strings.Contains(strings.ToLower(n.Name), "eventreason") {
					continue
				}
				if i >= len(vs.Values) {
					continue
				}
				if s, ok := stringLit(vs.Values[i]); ok {
					out[n.Name] = s
				}
			}
		}
	}
	return out
}

// isEventCall reports whether call is one of:
//   - r.emitEvent / r.emitEventf
//   - r.Recorder.Event / r.Recorder.Eventf
//
// Receiver name is irrelevant; we match on the trailing method name and, for
// Recorder.* forms, the intermediate "Recorder" selector.
func isEventCall(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	switch sel.Sel.Name {
	case "emitEvent", "emitEventf":
		return true
	case "Event", "Eventf":
		// Inner selector must be `.Recorder` to avoid matching unrelated
		// `.Event*` methods on other types.
		inner, ok := sel.X.(*ast.SelectorExpr)
		if !ok {
			return false
		}
		return inner.Sel.Name == "Recorder"
	}
	return false
}

// resolveEventType maps the second arg to "Normal" / "Warning" by recognising
// `corev1.EventTypeNormal` / `corev1.EventTypeWarning`. Anything else returns
// "" (caller skips the row — there are no such cases in this repo today, and
// silently dropping is preferable to a misleading row).
func resolveEventType(e ast.Expr) string {
	sel, ok := e.(*ast.SelectorExpr)
	if !ok {
		return ""
	}
	switch sel.Sel.Name {
	case "EventTypeNormal":
		return "Normal"
	case "EventTypeWarning":
		return "Warning"
	}
	return ""
}

// resolveReason returns the string value of the reason argument, looking it
// up in the const map for identifiers and unquoting string literals directly.
func resolveReason(e ast.Expr, consts map[string]string) string {
	switch v := e.(type) {
	case *ast.BasicLit:
		if v.Kind == token.STRING {
			s, err := strconv.Unquote(v.Value)
			if err == nil {
				return s
			}
		}
	case *ast.Ident:
		if s, ok := consts[v.Name]; ok {
			return s
		}
		return v.Name // surfaced as-is for visibility
	}
	return ""
}

// controllerName maps a controller filename to the user-facing CRD Kind.
// The mapping is explicit because two filenames don't camel-case to the
// expected Kind: policy_controller.go owns RemoteAttributePolicy, and
// external_sync_controller.go owns ExternalAttributeSync.
func controllerName(filename string) string {
	base := strings.TrimSuffix(filename, "_controller.go")
	switch base {
	case "policy":
		return "RemoteAttributePolicy"
	case "external_sync":
		return "ExternalAttributeSync"
	case "tenant_policy":
		return "TenantPolicy"
	case "collector_discovery":
		return "CollectorDiscovery"
	}
	parts := strings.Split(base, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
