package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// flagDecl captures one `flag.<Type>Var(&v, "name", default, "usage")` call.
type flagDecl struct {
	Name       string // CLI flag name, e.g. "metrics-bind-address"
	Type       string // String, Bool, Int, Float64, Duration
	Default    string // source-text rendering of the default expression
	Usage      string // concatenated usage string
	Source     string // file:line where the flag is declared (relative to root)
	InChart    string // "yes" | "no" | "conditional"
	ChartLines string // line numbers in deployment.yaml where the flag appears
}

// generateFlags is the entrypoint for the `flags` subcommand. It parses
// cmd/main.go for flag.*Var calls and the rendered deployment template for
// chart coverage, then renders docs/flags.md from a text/template.
func generateFlags(root string) ([]byte, error) {
	mainPath := filepath.Join(root, "cmd", "main.go")
	flags, err := extractFlags(root, mainPath)
	if err != nil {
		return nil, err
	}
	chartCoverage, err := scanChartArgs(filepath.Join(
		root,
		"charts",
		"fleet-management-operator",
		"templates",
		"deployment.yaml",
	))
	if err != nil {
		return nil, fmt.Errorf("scan chart deployment: %w", err)
	}
	for i := range flags {
		c, ok := chartCoverage[flags[i].Name]
		switch {
		case !ok:
			flags[i].InChart = "no"
		case c.conditional:
			flags[i].InChart = "conditional"
			flags[i].ChartLines = c.linesString()
		default:
			flags[i].InChart = "yes"
			flags[i].ChartLines = c.linesString()
		}
	}
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })

	tmpl, err := template.New("flags").Parse(flagsTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Flags []flagDecl
	}{Flags: flags}); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const flagsTemplate = `<!--
Auto-generated by hack/docgen. Do not edit by hand.
Run ` + "`make docs`" + ` after touching flag declarations in cmd/main.go.
-->

# Manager Flags

The ` + "`manager`" + ` binary accepts the flags listed below. They are also surfaced
through the Helm chart's ` + "`controllers.*`" + ` and ` + "`fleetManagement.*`" + ` value blocks
where applicable. Defaults are conservative: every controller other than
` + "`pipeline`" + ` is opt-in.

| Flag | Type | Default | Set by chart? | Description | Source |
| --- | --- | --- | --- | --- | --- |
{{- range .Flags }}
` + flagsTemplateRow + `
{{- end }}

## Chart coverage

The "Set by chart?" column reflects whether the rendered deployment passes the
flag to the manager binary today.

- **yes** — the flag is unconditionally rendered into the deployment ` + "`args:`" + ` list.
- **conditional** — the flag is only rendered under a Helm ` + "`if`" + ` guard
  (typical for cert / leader-election / metrics-secure flags). Whether you see
  it on a given install depends on values.
- **no** — the flag is never set by the chart. Either the default is the
  intended value for chart users (and the flag is reserved for ` + "`make run`" + `
  workflows or out-of-tree integrations), or the chart is missing coverage.
  ` + "`no`" + ` rows are worth checking against new feature flags.
`

const flagsTemplateRow = "| `--{{ .Name }}` | {{ .Type }} | {{ if .Default }}`{{ .Default }}`" +
	"{{ else }}—{{ end }} | " +
	"{{ .InChart }}{{ if .ChartLines }} ({{ .ChartLines }}){{ end }} | " +
	"{{ .Usage }} | [{{ .Source }}](../{{ .Source }}) |"

func extractFlags(root, path string) ([]flagDecl, error) {
	fset := token.NewFileSet()
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	relPath, err := filepath.Rel(root, path)
	if err != nil {
		relPath = path
	}

	var out []flagDecl
	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		pkg, ok := sel.X.(*ast.Ident)
		if !ok || pkg.Name != "flag" {
			return true
		}
		fnName := sel.Sel.Name
		typ, isVar := flagType(fnName)
		if !isVar {
			return true
		}
		if len(call.Args) != 4 {
			return true // not the *Var(&v, name, default, usage) form
		}
		nameLit, ok := call.Args[1].(*ast.BasicLit)
		if !ok || nameLit.Kind != token.STRING {
			return true
		}
		name, err := strconv.Unquote(nameLit.Value)
		if err != nil {
			return true
		}
		def := exprText(fset, call.Args[2])
		usage := concatStringExpr(call.Args[3])
		pos := fset.Position(call.Pos())
		out = append(out, flagDecl{
			Name:    name,
			Type:    typ,
			Default: def,
			Usage:   strings.ReplaceAll(usage, "|", "\\|"),
			Source:  fmt.Sprintf("%s:%d", relPath, pos.Line),
		})
		return true
	})
	return out, nil
}

// flagType maps "StringVar" → "string" and reports whether the function is
// a flag.*Var setter. Anything else (flag.String, flag.Parse, …) is ignored.
func flagType(fn string) (string, bool) {
	switch fn {
	case "StringVar":
		return "string", true
	case "BoolVar":
		return "bool", true
	case "IntVar":
		return "int", true
	case "Int64Var":
		return "int64", true
	case "Float64Var":
		return "float64", true
	case "DurationVar":
		return "duration", true
	case "Uint64Var":
		return "uint64", true
	}
	return "", false
}

// exprText renders an AST expression back to source-equivalent text. It is the
// cleanest way to handle compound defaults like `15*time.Second` or named
// constants without re-implementing constant evaluation.
func exprText(fset *token.FileSet, e ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, e); err != nil {
		return "?"
	}
	s := buf.String()
	// Trim quotes from string literals so the table reads "0" not `"0"`.
	if u, err := strconv.Unquote(s); err == nil {
		return u
	}
	return s
}

// concatStringExpr handles the common "long flag usage" idiom where the usage
// string is `"first part " + "second part"` split across source lines. It walks
// nested BinaryExpr Add chains and returns the concatenated literal value;
// non-literal operands are rendered via exprText as a fallback.
func concatStringExpr(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.BasicLit:
		if v.Kind == token.STRING {
			s, err := strconv.Unquote(v.Value)
			if err == nil {
				return s
			}
		}
		return v.Value
	case *ast.BinaryExpr:
		if v.Op == token.ADD {
			return concatStringExpr(v.X) + concatStringExpr(v.Y)
		}
	}
	return "?"
}

// chartCoverage records where a flag appears in the deployment template, and
// whether it's nested inside a Helm conditional block. Conditional placement
// matters: it tells users that the flag's presence depends on values, not
// solely on the operator binary's defaults.
type chartCoverage struct {
	conditional bool
	lines       []int
}

func (c chartCoverage) linesString() string {
	out := make([]string, len(c.lines))
	for i, l := range c.lines {
		out[i] = fmt.Sprintf("L%d", l)
	}
	return strings.Join(out, ", ")
}

// scanChartArgs reads the deployment template line-by-line and tracks Helm
// `{{- if … }}` / `{{- end }}` nesting depth. A flag mention inside a non-zero
// nesting depth (other than the surrounding spec) is considered conditional.
// The container-args section is the relevant scope; we identify any `--name`
// occurrence as a hit, which is sufficient for the binary yes/no check.
func scanChartArgs(path string) (map[string]chartCoverage, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := map[string]chartCoverage{}
	depth := 0
	for i, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "{{- if ") || strings.HasPrefix(trimmed, "{{ if ") {
			depth++
		}
		if strings.HasPrefix(trimmed, "{{- end") || strings.HasPrefix(trimmed, "{{ end") {
			if depth > 0 {
				depth--
			}
		}
		// Look for `--<flag-name>` patterns in the actual content (not just
		// Helm conditionals). The form is consistently `- --<flag>=...`.
		if idx := strings.Index(line, "--"); idx >= 0 {
			rest := line[idx+2:]
			end := strings.IndexAny(rest, "= \t")
			if end < 0 {
				end = len(rest)
			}
			name := rest[:end]
			if isFlagName(name) {
				c := out[name]
				if depth > 0 {
					c.conditional = true
				}
				c.lines = append(c.lines, i+1)
				out[name] = c
			}
		}
	}
	return out, nil
}

// isFlagName checks the candidate is a plausible CLI flag (kebab-case ASCII).
// This filters out random `--`-introduced text in Helm template comments.
func isFlagName(s string) bool {
	if len(s) < 2 {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9':
		case r == '-':
		default:
			return false
		}
	}
	return strings.Contains(s, "-")
}
