package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// metricDecl captures one Prometheus metric registration.
type metricDecl struct {
	Name    string   // metric name from Opts.Name (e.g. "fleet_api_request_duration_seconds")
	Kind    string   // Counter, Histogram, Gauge, Summary
	IsVec   bool     // true for *Vec metrics that carry a label list
	Help    string   // Opts.Help (one-line summary)
	Labels  []string // empty for non-Vec
	Buckets string   // human-readable bucket boundaries (histograms only)
	Source  string   // file:line of the registration
}

// generateMetrics is the entrypoint for the `metrics` subcommand. It scans
// pkg/fleetclient/metrics.go and internal/controller/metrics.go for
// `prometheus.New*` calls, extracts the metric definition, and renders a
// reference table grouped by file (which corresponds to subsystem: fleet-api
// vs controller-side).
func generateMetrics(root string) ([]byte, error) {
	groups := []struct {
		Title string
		Path  string
		Intro string
	}{
		{
			Title: "Fleet API client",
			Path:  filepath.Join("pkg", "fleetclient", "metrics.go"),
			Intro: "Latency, error rate, and rate-limiter saturation for outbound calls to the Fleet Management API. Use these to alert on Fleet API regressions.",
		},
		{
			Title: "Controller reconciliation",
			Path:  filepath.Join("internal", "controller", "metrics.go"),
			Intro: "Per-CRD reconcile outcome counters and gauges that track owned attributes / discovered collectors. Use these to alert on reconciliation health.",
		},
	}
	type rendered struct {
		Title   string
		Intro   string
		Metrics []metricDecl
	}
	var out []rendered
	for _, g := range groups {
		full := filepath.Join(root, g.Path)
		metrics, err := extractMetrics(root, full)
		if err != nil {
			return nil, fmt.Errorf("extract %s: %w", g.Path, err)
		}
		sort.Slice(metrics, func(i, j int) bool { return metrics[i].Name < metrics[j].Name })
		out = append(out, rendered{Title: g.Title, Intro: g.Intro, Metrics: metrics})
	}

	tmpl, err := template.New("metrics").Parse(metricsTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, out); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const metricsTemplate = `<!--
Auto-generated by hack/docgen. Do not edit by hand.
Run ` + "`make docs`" + ` after touching prometheus.New* calls in pkg/fleetclient/metrics.go
or internal/controller/metrics.go.
-->

# Metrics Reference

The operator exposes Prometheus metrics on the manager binary's metrics
endpoint (defaults to ` + "`:8443`" + ` HTTPS or ` + "`:8080`" + ` HTTP, see ` + "`--metrics-bind-address`" + `
in [flags.md](flags.md)). All metric names are stable across patch releases;
new labels may be added.

Histogram bucket boundaries are tuned to the operator's 30s HTTP timeout —
anything in the 20-30s range indicates rate-limiter saturation or upstream
slowness, both of which warrant paging.

{{ range . }}
## {{ .Title }}

{{ .Intro }}

| Metric | Kind | Labels | Buckets | Description | Source |
| --- | --- | --- | --- | --- | --- |
{{- range .Metrics }}
| ` + "`{{ .Name }}`" + ` | {{ .Kind }}{{ if .IsVec }}Vec{{ end }} | {{ if .Labels }}{{ range $i, $l := .Labels }}{{ if $i }}, {{ end }}` + "`{{ $l }}`" + `{{ end }}{{ else }}—{{ end }} | {{ if .Buckets }}` + "`{{ .Buckets }}`" + `{{ else }}—{{ end }} | {{ .Help }} | [{{ .Source }}](../{{ .Source }}) |
{{- end }}
{{ end }}
`

// extractMetrics walks one Go source file for prometheus.New<Counter|Histogram|Gauge|Summary>[Vec]
// calls. The current codebase consistently uses the literal-Opts-struct form,
// so we reach into the AST to pull Name / Help / Buckets directly. Anything
// non-literal short-circuits with a descriptive error so we fail loudly on
// unsupported patterns rather than silently dropping metrics.
func extractMetrics(root, path string) ([]metricDecl, error) {
	fset := token.NewFileSet()
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	relPath, err := filepath.Rel(root, path)
	if err != nil {
		relPath = path
	}

	var out []metricDecl
	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		pkg, ok := sel.X.(*ast.Ident)
		if !ok || pkg.Name != "prometheus" {
			return true
		}
		kind, isVec, ok := metricKind(sel.Sel.Name)
		if !ok {
			return true
		}
		if len(call.Args) < 1 {
			return true
		}
		opts, ok := call.Args[0].(*ast.CompositeLit)
		if !ok {
			return true
		}
		name, help, buckets, err := readMetricOpts(opts)
		if err != nil {
			// Surface the error verbatim so the make target fails with a
			// useful pointer rather than silently swallowing a metric.
			pos := fset.Position(call.Pos())
			fmt.Fprintf(os.Stderr, "warn: %s:%d: %v\n", relPath, pos.Line, err)
			return true
		}
		var labels []string
		if isVec && len(call.Args) >= 2 {
			labels = readStringSlice(call.Args[1])
		}
		pos := fset.Position(call.Pos())
		out = append(out, metricDecl{
			Name:    name,
			Kind:    kind,
			IsVec:   isVec,
			Help:    strings.ReplaceAll(help, "|", "\\|"),
			Labels:  labels,
			Buckets: buckets,
			Source:  fmt.Sprintf("%s:%d", relPath, pos.Line),
		})
		return true
	})
	return out, nil
}

// metricKind maps "NewCounterVec" → ("Counter", true, true). Returns ok=false
// for anything that is not a recognised Prometheus constructor.
func metricKind(fn string) (kind string, isVec, ok bool) {
	const prefix = "New"
	if !strings.HasPrefix(fn, prefix) {
		return "", false, false
	}
	rest := strings.TrimPrefix(fn, prefix)
	isVec = strings.HasSuffix(rest, "Vec")
	rest = strings.TrimSuffix(rest, "Vec")
	switch rest {
	case "Counter", "Histogram", "Gauge", "Summary":
		return rest, isVec, true
	}
	return "", false, false
}

// readMetricOpts pulls Name, Help, and Buckets from a literal
// prometheus.<Kind>Opts{...} struct. Buckets is rendered as a
// comma-separated list to match the source-text shape so operators can copy
// it directly into PromQL.
func readMetricOpts(opts *ast.CompositeLit) (name, help, buckets string, err error) {
	for _, elt := range opts.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Name":
			s, ok := stringLit(kv.Value)
			if !ok {
				return "", "", "", fmt.Errorf("Opts.Name is not a string literal")
			}
			name = s
		case "Help":
			s, ok := stringLit(kv.Value)
			if !ok {
				return "", "", "", fmt.Errorf("Opts.Help is not a string literal")
			}
			help = s
		case "Buckets":
			buckets = renderBuckets(kv.Value)
		}
	}
	if name == "" {
		return "", "", "", fmt.Errorf("Opts.Name not found")
	}
	return name, help, buckets, nil
}

func stringLit(e ast.Expr) (string, bool) {
	lit, ok := e.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	s, err := strconv.Unquote(lit.Value)
	if err != nil {
		return "", false
	}
	return s, true
}

// renderBuckets stringifies a `[]float64{...}` literal as a compact
// comma-separated list. Non-literal bucket expressions (e.g. references to
// prometheus.DefBuckets) round-trip as their source text so the doc still
// reflects the actual value.
func renderBuckets(e ast.Expr) string {
	cl, ok := e.(*ast.CompositeLit)
	if !ok {
		return "(non-literal)"
	}
	parts := make([]string, 0, len(cl.Elts))
	for _, el := range cl.Elts {
		switch v := el.(type) {
		case *ast.BasicLit:
			parts = append(parts, v.Value)
		case *ast.SelectorExpr, *ast.Ident:
			// Ignore non-numeric entries; should not occur for the current code.
		}
	}
	return strings.Join(parts, ", ")
}

// readStringSlice extracts ["a","b","c"] from a `[]string{"a","b","c"}` literal.
func readStringSlice(e ast.Expr) []string {
	cl, ok := e.(*ast.CompositeLit)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(cl.Elts))
	for _, el := range cl.Elts {
		if s, ok := stringLit(el); ok {
			out = append(out, s)
		}
	}
	return out
}
