package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// sampleDecl describes one config/samples/*.yaml file.
type sampleDecl struct {
	File        string // path relative to repo root, e.g. "config/samples/policy_sample.yaml"
	Filename    string // basename for anchor / table-of-contents
	Kind        string // CRD Kind from `kind: …` line
	Name        string // metadata.name
	Description string // from `# Description: …` header
	Body        string // file contents (verbatim, without the description comment)
}

// generateSamples is the entrypoint for the `samples` subcommand. It walks
// every .yaml in config/samples/ (excluding kustomization.yaml and the
// invalid/ subdirectory), reads the leading `# Description: …` comment, and
// embeds each file under a Kind-grouped index. A missing description fails
// the generator with a descriptive error so contributors can't add a new
// sample without explaining what it demonstrates.
func generateSamples(root string) ([]byte, error) {
	dir := filepath.Join(root, "config", "samples")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	samples := make([]sampleDecl, 0, len(entries))
	for _, ent := range entries {
		if ent.IsDir() || ent.Name() == "kustomization.yaml" || !strings.HasSuffix(ent.Name(), ".yaml") {
			continue
		}
		full := filepath.Join(dir, ent.Name())
		s, err := readSample(root, full)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", ent.Name(), err)
		}
		samples = append(samples, s)
	}
	sort.Slice(samples, func(i, j int) bool {
		if samples[i].Kind != samples[j].Kind {
			return samples[i].Kind < samples[j].Kind
		}
		return samples[i].Name < samples[j].Name
	})

	tmpl, err := template.New("samples").Funcs(template.FuncMap{
		"anchor": markdownAnchor,
	}).Parse(samplesTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, samples); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const samplesTemplate = `<!--
Auto-generated by hack/docgen. Do not edit by hand.
Run ` + "`make docs`" + ` after touching files in config/samples/. Each sample must
carry a leading "# Description: …" comment; the generator fails otherwise.
-->

# Sample CRs

Working examples of each CRD this operator manages. Apply with:

` + "```" + `
kubectl apply -n <namespace> -f config/samples/<namespaced-file>.yaml
kubectl apply -f config/samples/tenant_policy_sample.yaml
` + "```" + `

Namespaced samples intentionally omit ` + "`metadata.namespace`" + `. Apply them
to the namespace that should own the CR. ` + "`TenantPolicy`" + ` is cluster-scoped
and must not carry a namespace.

For invalid-spec fixtures used by webhook tests, see
[config/samples/invalid/README.md](../config/samples/invalid/README.md).

## Index

{{- range . }}
- [{{ .Kind }}: ` + "`{{ .Name }}`" + `](#{{ anchor .Kind }}-{{ anchor .Name }}) — {{ .Description }}
{{- end }}

{{ range . }}
## {{ .Kind }}: ` + "`{{ .Name }}`" + `

{{ .Description }}

Source: [{{ .File }}](../{{ .File }})

` + "```" + `yaml
{{ .Body }}
` + "```" + `
{{ end }}
`

// readSample parses one YAML file: extracts the leading `# Description:` line,
// the kind: and metadata.name: fields, and the body (verbatim, with the
// description comment stripped so it doesn't double in the embedded snippet).
func readSample(root, path string) (sampleDecl, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return sampleDecl{}, fmt.Errorf("read: %w", err)
	}
	rel, err := filepath.Rel(root, path)
	if err != nil {
		rel = path
	}

	var (
		desc       string
		kind       string
		name       string
		seenName   bool
		bodyLines  []string
		descPrefix = "# Description:"
	)
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		line := scanner.Text()
		if desc == "" {
			if after, ok := strings.CutPrefix(strings.TrimSpace(line), descPrefix); ok {
				desc = strings.TrimSpace(after)
				continue // drop description comment from rendered body
			}
		}
		bodyLines = append(bodyLines, line)
		if after, ok := strings.CutPrefix(line, "kind:"); ok {
			kind = strings.TrimSpace(after)
		}
		// metadata.name is the FIRST top-level `name:` after `metadata:`.
		// We detect "indented `name:` after we've seen `metadata:`".
		trimmed := strings.TrimLeft(line, " \t")
		if after, ok := strings.CutPrefix(trimmed, "name:"); !seenName && ok && line != trimmed {
			name = strings.TrimSpace(after)
			seenName = true
		}
	}
	if err := scanner.Err(); err != nil {
		return sampleDecl{}, fmt.Errorf("scan: %w", err)
	}
	if desc == "" {
		return sampleDecl{}, fmt.Errorf("missing leading '# Description: …' comment in %s", rel)
	}
	if kind == "" {
		return sampleDecl{}, fmt.Errorf("no `kind:` field in %s", rel)
	}
	if name == "" {
		return sampleDecl{}, fmt.Errorf("no metadata.name in %s", rel)
	}
	body := strings.Join(bodyLines, "\n")
	body = strings.TrimRight(body, "\n") // template adds the trailing fence newline
	return sampleDecl{
		File:        rel,
		Filename:    filepath.Base(path),
		Kind:        kind,
		Name:        name,
		Description: desc,
		Body:        body,
	}, nil
}

// markdownAnchor lowercases and replaces non-anchor characters with hyphens
// so generated header anchors match GitHub's auto-anchor algorithm closely
// enough that the index links work in browsers.
func markdownAnchor(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out = append(out, r)
		case r == '-' || r == '_':
			out = append(out, r)
		case r == ' ':
			out = append(out, '-')
		}
	}
	return string(out)
}
