---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-collector
  failurePolicy: Fail
  name: vcollector.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectors
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-collectordiscovery
  failurePolicy: Fail
  name: vcollectordiscovery.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectordiscoveries
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-externalattributesync
  failurePolicy: Fail
  name: vexternalattributesync.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - externalattributesyncs
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-pipeline
  failurePolicy: Fail
  name: vpipeline.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-pipelinediscovery
  failurePolicy: Fail
  name: vpipelinediscovery.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelinediscoveries
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-remoteattributepolicy
  failurePolicy: Fail
  name: vremoteattributepolicy.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteattributepolicies
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetmanagement-grafana-com-v1alpha1-tenantpolicy
  failurePolicy: Fail
  name: vtenantpolicy.kb.io
  rules:
  - apiGroups:
    - fleetmanagement.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenantpolicies
  sideEffects: None
  timeoutSeconds: 5
