---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleetmanagement.grafana.com
  resources:
  - collectordiscoveries
  - collectors
  - externalattributesyncs
  - pipelines
  - remoteattributepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleetmanagement.grafana.com
  resources:
  - collectordiscoveries/status
  - collectors/status
  - externalattributesyncs/status
  - pipelines/status
  - remoteattributepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fleetmanagement.grafana.com
  resources:
  - collectors/finalizers
  - pipelines/finalizers
  verbs:
  - update
