name: actionlint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
permissions: {}
jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@main
